name: CD
run-name: ${{ github.event.workflow_run.head_commit.message }}
on:
  workflow_run:
    branches: [main]
    workflows: ["Rust CI"]
    types:
      - completed

permissions:
  contents: read
  packages: write
  statuses: write

jobs:
  build-minion-x86-64:
    runs-on:
      labels: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.ACCESS_FRAMEWORK_TOKEN }}
          submodules: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push x86-64 image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Containerfile.minion
          push: true
          tags: ghcr.io/minionrt/default-minion:x86-64-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
